### ISSUE TITLE
Feature request: H2 folding

### ISSUE THREAD

**Issue by focusaurus** [JoseBlanca/markdown-folding#2]
Would you consider adding the ability to fold at H2 level?

I typically only have a single H1 at the top of my document, and although there are [complicated best practices here](https://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824) I think it makes sense for markdown and most markdown CSS makes H1 so huge that I wouldn't want to use a bunch of them. Thus in it's current state this plugin is useless for most of my documents as it folds the entire document or nothing at all.

**Comment by GregHilston** [comment]
@focusaurus Have you tried simply indenting to create a new fold option?

**Comment by JoseBlanca** [comment]
This is a really great idea. In fact I'm having the same issue with my documents. I'll try to do it when I have sometime.

**Comment by JoseBlanca** [comment]
I've implemented h2 folding. I've also modified the folding cycle, I think that now is more usefull. Thanks for the suggestions.

**Comment by GregHilston** [comment]
Nice job, thanks @JoseBlanca

**Comment by focusaurus** [comment]
Thanks! I'll test it out once it's published to apm. I don't think it's been published yet as far as I can tell.
