### ISSUE TITLE
Don't fold the last line

### ISSUE THREAD

**Issue by saivan** [JoseBlanca/markdown-folding#5]
Would it be possible to add an option to avoid folding the line before the next h1, this just stops everything from looking too cramped. For example, if I had the following document:

```md
# Hello

this is some text
 
# Hello Again 

Some more text here

```

Calling fold h1 should do this:

```md

# Hello {...}

# Hello Again {...}

```

Right now it does this:

```md

# Hello {...}
# Hello Again {...}
```

Which is just really cramped.

**Comment by JoseBlanca** [comment]
I've merged your pr. Thanks!

**Comment by saivan** [comment]
No problem! My pleasure. Its not the worlds most robust code, but it should do the trick.
